<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DSPSeedScanner.Core\DSPSeedScanner.Core.csproj" />
    <ProjectReference Include="..\..\src\DSPSeedScanner.Runtime\DSPSeedScanner.Runtime.csproj" />
  </ItemGroup>
</Project>
